//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.Apophysis.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class CommonSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static CommonSettings defaultInstance = ((CommonSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new CommonSettings())));
        
        public static CommonSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PluginDirectoryName {
            get {
                return ((string)(this["PluginDirectoryName"]));
            }
            set {
                this["PluginDirectoryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apo7x")]
        public string NamePrefix {
            get {
                return ((string)(this["NamePrefix"]));
            }
            set {
                this["NamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUnknownAttributesMessage {
            get {
                return ((bool)(this["ShowUnknownAttributesMessage"]));
            }
            set {
                this["ShowUnknownAttributesMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VariationsIn15CStyle {
            get {
                return ((bool)(this["VariationsIn15CStyle"]));
            }
            set {
                this["VariationsIn15CStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int JpegQuality {
            get {
                return ((int)(this["JpegQuality"]));
            }
            set {
                this["JpegQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnablePngTransparency {
            get {
                return ((bool)(this["EnablePngTransparency"]));
            }
            set {
                this["EnablePngTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDeleteConfirmation {
            get {
                return ((bool)(this["ShowDeleteConfirmation"]));
            }
            set {
                this["ShowDeleteConfirmation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCancelRenderConfirmation {
            get {
                return ((bool)(this["ShowCancelRenderConfirmation"]));
            }
            set {
                this["ShowCancelRenderConfirmation"] = value;
            }
        }
    }
}
