//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.Apophysis.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class ViewSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ViewSettings defaultInstance = ((ViewSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ViewSettings())));
        
        public static ViewSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BatchListUsePreviews {
            get {
                return ((bool)(this["BatchListUsePreviews"]));
            }
            set {
                this["BatchListUsePreviews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int BatchListPreviewSize {
            get {
                return ((int)(this["BatchListPreviewSize"]));
            }
            set {
                this["BatchListPreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMainToolbarVisible {
            get {
                return ((bool)(this["IsMainToolbarVisible"]));
            }
            set {
                this["IsMainToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMainStatusbarVisible {
            get {
                return ((bool)(this["IsMainStatusbarVisible"]));
            }
            set {
                this["IsMainStatusbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int BatchListSize {
            get {
                return ((int)(this["BatchListSize"]));
            }
            set {
                this["BatchListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBatchListVisible {
            get {
                return ((bool)(this["IsBatchListVisible"]));
            }
            set {
                this["IsBatchListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowGuidelines {
            get {
                return ((bool)(this["ShowGuidelines"]));
            }
            set {
                this["ShowGuidelines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTransparency {
            get {
                return ((bool)(this["ShowTransparency"]));
            }
            set {
                this["ShowTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncMainWindowWithCanvasSize {
            get {
                return ((bool)(this["SyncMainWindowWithCanvasSize"]));
            }
            set {
                this["SyncMainWindowWithCanvasSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FitMainPreviewImage {
            get {
                return ((bool)(this["FitMainPreviewImage"]));
            }
            set {
                this["FitMainPreviewImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaintainCanvasAspectRatio {
            get {
                return ((bool)(this["MaintainCanvasAspectRatio"]));
            }
            set {
                this["MaintainCanvasAspectRatio"] = value;
            }
        }
    }
}
