//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.Apophysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double EditorMoveDistance {
            get {
                return ((double)(this["EditorMoveDistance"]));
            }
            set {
                this["EditorMoveDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public double EditorRotateAngle {
            get {
                return ((double)(this["EditorRotateAngle"]));
            }
            set {
                this["EditorRotateAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("125")]
        public double EditorScaleRatio {
            get {
                return ((double)(this["EditorScaleRatio"]));
            }
            set {
                this["EditorScaleRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditorLockAxes {
            get {
                return ((bool)(this["EditorLockAxes"]));
            }
            set {
                this["EditorLockAxes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorShowRulers {
            get {
                return ((bool)(this["EditorShowRulers"]));
            }
            set {
                this["EditorShowRulers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorShowVariationPreview {
            get {
                return ((bool)(this["EditorShowVariationPreview"]));
            }
            set {
                this["EditorShowVariationPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorAutoZoom {
            get {
                return ((bool)(this["EditorAutoZoom"]));
            }
            set {
                this["EditorAutoZoom"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Plugins")]
        public string PluginDirectoryName {
            get {
                return ((string)(this["PluginDirectoryName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double EditorVariationPreviewDensity {
            get {
                return ((double)(this["EditorVariationPreviewDensity"]));
            }
            set {
                this["EditorVariationPreviewDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double EditorVariationPreviewRange {
            get {
                return ((double)(this["EditorVariationPreviewRange"]));
            }
            set {
                this["EditorVariationPreviewRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apo7x")]
        public string NamePrefix {
            get {
                return ((string)(this["NamePrefix"]));
            }
            set {
                this["NamePrefix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BatchListUsePreviews {
            get {
                return ((bool)(this["BatchListUsePreviews"]));
            }
            set {
                this["BatchListUsePreviews"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int BatchListPreviewSize {
            get {
                return ((int)(this["BatchListPreviewSize"]));
            }
            set {
                this["BatchListPreviewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double BatchListPreviewDensity {
            get {
                return ((double)(this["BatchListPreviewDensity"]));
            }
            set {
                this["BatchListPreviewDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double PreviewLowQualityDensity {
            get {
                return ((double)(this["PreviewLowQualityDensity"]));
            }
            set {
                this["PreviewLowQualityDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PreviewMediumQualityDensity {
            get {
                return ((double)(this["PreviewMediumQualityDensity"]));
            }
            set {
                this["PreviewMediumQualityDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double PreviewHighQualityDensity {
            get {
                return ((double)(this["PreviewHighQualityDensity"]));
            }
            set {
                this["PreviewHighQualityDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int EditorPreviewDensityLevel {
            get {
                return ((int)(this["EditorPreviewDensityLevel"]));
            }
            set {
                this["EditorPreviewDensityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditorVariationPreviewApplyPostTransform {
            get {
                return ((bool)(this["EditorVariationPreviewApplyPostTransform"]));
            }
            set {
                this["EditorVariationPreviewApplyPostTransform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MainPreviewDensity {
            get {
                return ((int)(this["MainPreviewDensity"]));
            }
            set {
                this["MainPreviewDensity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int FlamePropertiesPreviewDensityLevel {
            get {
                return ((int)(this["FlamePropertiesPreviewDensityLevel"]));
            }
            set {
                this["FlamePropertiesPreviewDensityLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MiniPreviewUpdateResolution {
            get {
                return ((int)(this["MiniPreviewUpdateResolution"]));
            }
            set {
                this["MiniPreviewUpdateResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMainToolbarVisible {
            get {
                return ((bool)(this["IsMainToolbarVisible"]));
            }
            set {
                this["IsMainToolbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMainStatusbarVisible {
            get {
                return ((bool)(this["IsMainStatusbarVisible"]));
            }
            set {
                this["IsMainStatusbarVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int BatchListSize {
            get {
                return ((int)(this["BatchListSize"]));
            }
            set {
                this["BatchListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsBatchListVisible {
            get {
                return ((bool)(this["IsBatchListVisible"]));
            }
            set {
                this["IsBatchListVisible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainPreviewShowGuidelines {
            get {
                return ((bool)(this["MainPreviewShowGuidelines"]));
            }
            set {
                this["MainPreviewShowGuidelines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainPreviewShowTransparency {
            get {
                return ((bool)(this["MainPreviewShowTransparency"]));
            }
            set {
                this["MainPreviewShowTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainPreviewFitImage {
            get {
                return ((bool)(this["MainPreviewFitImage"]));
            }
            set {
                this["MainPreviewFitImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CameraEditMode {
            get {
                return ((int)(this["CameraEditMode"]));
            }
            set {
                this["CameraEditMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CameraEditUseScale {
            get {
                return ((bool)(this["CameraEditUseScale"]));
            }
            set {
                this["CameraEditUseScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SizePreset1 {
            get {
                return ((global::System.Drawing.Size)(this["SizePreset1"]));
            }
            set {
                this["SizePreset1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SizePreset2 {
            get {
                return ((global::System.Drawing.Size)(this["SizePreset2"]));
            }
            set {
                this["SizePreset2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size SizePreset3 {
            get {
                return ((global::System.Drawing.Size)(this["SizePreset3"]));
            }
            set {
                this["SizePreset3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncMainWindowWithCanvasSize {
            get {
                return ((bool)(this["SyncMainWindowWithCanvasSize"]));
            }
            set {
                this["SyncMainWindowWithCanvasSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MaintainCanvasAspectRatio {
            get {
                return ((bool)(this["MaintainCanvasAspectRatio"]));
            }
            set {
                this["MaintainCanvasAspectRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowUnknownAttributesMessage {
            get {
                return ((bool)(this["ShowUnknownAttributesMessage"]));
            }
            set {
                this["ShowUnknownAttributesMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%UserProfile%\\ApophysisAutosave.flame")]
        public string AutosavePath {
            get {
                return ((string)(this["AutosavePath"]));
            }
            set {
                this["AutosavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AutosaveThreshold {
            get {
                return ((int)(this["AutosaveThreshold"]));
            }
            set {
                this["AutosaveThreshold"] = value;
            }
        }
    }
}
