//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.Apophysis.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class AutosaveSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AutosaveSettings defaultInstance = ((AutosaveSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AutosaveSettings())));
        
        public static AutosaveSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%UserProfile%\\ApophysisAutosave.flame")]
        public string TargetPath {
            get {
                return ((string)(this["TargetPath"]));
            }
            set {
                this["TargetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int Threshold {
            get {
                return ((int)(this["Threshold"]));
            }
            set {
                this["Threshold"] = value;
            }
        }
    }
}
