// *****************************************************************************
// * This is an automatically generated header file for UI Element definition  *
// * resource symbols and values. Please do not modify manually.               *
// *****************************************************************************

#pragma once

#define ApplicationMenu 2 
#define ApplicationMenu_LabelTitle_RESID 60001
#define StartMenu 3 
#define StartMenu_LabelTitle_RESID 60002
#define FileMenuGroup 4 
#define FileMenuGroup_LabelTitle_RESID 60003
#define NewFlameCommand 5 
#define NewFlameCommand_LabelTitle_RESID 60004
#define NewFlameCommand_LabelDescription_RESID 60005
#define NewFlameCommand_Keytip_RESID 60006
#define NewFlameCommand_TooltipTitle_RESID 60007
#define NewFlameCommand_TooltipDescription_RESID 60008
#define NewFlameCommand_SmallImages_RESID 60009
#define NewFlameCommand_LargeImages_RESID 60010
#define OpenBatchCommand 6 
#define OpenBatchCommand_LabelTitle_RESID 60011
#define OpenBatchCommand_LabelDescription_RESID 60012
#define OpenBatchCommand_Keytip_RESID 60013
#define OpenBatchCommand_TooltipTitle_RESID 60014
#define OpenBatchCommand_TooltipDescription_RESID 60015
#define OpenBatchCommand_SmallImages_RESID 60016
#define OpenBatchCommand_LargeImages_RESID 60017
#define SaveFlameCommand 7 
#define SaveFlameCommand_LabelTitle_RESID 60018
#define SaveFlameCommand_LabelDescription_RESID 60019
#define SaveFlameCommand_Keytip_RESID 60020
#define SaveFlameCommand_TooltipTitle_RESID 60021
#define SaveFlameCommand_TooltipDescription_RESID 60022
#define SaveFlameCommand_SmallImages_RESID 60023
#define SaveFlameCommand_LargeImages_RESID 60024
#define SaveBatchCommand 8 
#define SaveBatchCommand_LabelTitle_RESID 60025
#define SaveBatchCommand_LabelDescription_RESID 60026
#define SaveBatchCommand_Keytip_RESID 60027
#define SaveBatchCommand_TooltipTitle_RESID 60028
#define SaveBatchCommand_TooltipDescription_RESID 60029
#define SaveBatchCommand_SmallImages_RESID 60030
#define SaveBatchCommand_LargeImages_RESID 60031
#define RestoreLastAutosaveCommand 9 
#define RestoreLastAutosaveCommand_LabelTitle_RESID 60032
#define RestoreLastAutosaveCommand_LabelDescription_RESID 60033
#define RestoreLastAutosaveCommand_Keytip_RESID 60034
#define RestoreLastAutosaveCommand_TooltipTitle_RESID 60035
#define RestoreLastAutosaveCommand_TooltipDescription_RESID 60036
#define RestoreLastAutosaveCommand_SmallImages_RESID 60037
#define RestoreLastAutosaveCommand_LargeImages_RESID 60038
#define EditMenuGroup 10 
#define EditMenuGroup_LabelTitle_RESID 60039
#define CopyCommand 11 
#define CopyCommand_LabelTitle_RESID 60040
#define CopyCommand_LabelDescription_RESID 60041
#define CopyCommand_Keytip_RESID 60042
#define CopyCommand_TooltipTitle_RESID 60043
#define CopyCommand_TooltipDescription_RESID 60044
#define CopyCommand_SmallImages_RESID 60045
#define CopyCommand_LargeImages_RESID 60046
#define PasteCommand 12 
#define PasteCommand_LabelTitle_RESID 60047
#define PasteCommand_LabelDescription_RESID 60048
#define PasteCommand_Keytip_RESID 60049
#define PasteCommand_TooltipTitle_RESID 60050
#define PasteCommand_TooltipDescription_RESID 60051
#define PasteCommand_SmallImages_RESID 60052
#define PasteCommand_LargeImages_RESID 60053
#define UndoCommand 13 
#define UndoCommand_LabelTitle_RESID 60054
#define UndoCommand_LabelDescription_RESID 60055
#define UndoCommand_Keytip_RESID 60056
#define UndoCommand_TooltipTitle_RESID 60057
#define UndoCommand_TooltipDescription_RESID 60058
#define UndoCommand_SmallImages_RESID 60059
#define UndoCommand_LargeImages_RESID 60060
#define RedoCommand 14 
#define RedoCommand_LabelTitle_RESID 60061
#define RedoCommand_LabelDescription_RESID 60062
#define RedoCommand_Keytip_RESID 60063
#define RedoCommand_TooltipTitle_RESID 60064
#define RedoCommand_TooltipDescription_RESID 60065
#define RedoCommand_SmallImages_RESID 60066
#define RedoCommand_LargeImages_RESID 60067
#define RenderMenuGroup 15 
#define RenderMenuGroup_LabelTitle_RESID 60068
#define RenderFlameCommand 16 
#define RenderFlameCommand_LabelTitle_RESID 60069
#define RenderFlameCommand_LabelDescription_RESID 60070
#define RenderFlameCommand_Keytip_RESID 60071
#define RenderFlameCommand_TooltipTitle_RESID 60072
#define RenderFlameCommand_TooltipDescription_RESID 60073
#define RenderFlameCommand_SmallImages_RESID 60074
#define RenderFlameCommand_LargeImages_RESID 60075
#define RenderBatchCommand 17 
#define RenderBatchCommand_LabelTitle_RESID 60076
#define RenderBatchCommand_LabelDescription_RESID 60077
#define RenderBatchCommand_Keytip_RESID 60078
#define RenderBatchCommand_TooltipTitle_RESID 60079
#define RenderBatchCommand_TooltipDescription_RESID 60080
#define RenderBatchCommand_SmallImages_RESID 60081
#define RenderBatchCommand_LargeImages_RESID 60082
#define ToolsMenuGroup 18 
#define ToolsMenuGroup_LabelTitle_RESID 60083
#define FullscreenPreviewCommand 19 
#define FullscreenPreviewCommand_LabelTitle_RESID 60084
#define FullscreenPreviewCommand_LabelDescription_RESID 60085
#define FullscreenPreviewCommand_Keytip_RESID 60086
#define FullscreenPreviewCommand_TooltipTitle_RESID 60087
#define FullscreenPreviewCommand_TooltipDescription_RESID 60088
#define FullscreenPreviewCommand_SmallImages_RESID 60089
#define FullscreenPreviewCommand_LargeImages_RESID 60090
#define ShowEditorCommand 20 
#define ShowEditorCommand_LabelTitle_RESID 60091
#define ShowEditorCommand_LabelDescription_RESID 60092
#define ShowEditorCommand_Keytip_RESID 60093
#define ShowEditorCommand_TooltipTitle_RESID 60094
#define ShowEditorCommand_TooltipDescription_RESID 60095
#define ShowEditorCommand_SmallImages_RESID 60096
#define ShowEditorCommand_LargeImages_RESID 60097
#define ShowAdjustmentCommand 21 
#define ShowAdjustmentCommand_LabelTitle_RESID 60098
#define ShowAdjustmentCommand_LabelDescription_RESID 60099
#define ShowAdjustmentCommand_Keytip_RESID 60100
#define ShowAdjustmentCommand_TooltipTitle_RESID 60101
#define ShowAdjustmentCommand_TooltipDescription_RESID 60102
#define ShowAdjustmentCommand_SmallImages_192__RESID 60103
#define ShowAdjustmentCommand_LargeImages_144__RESID 60104
#define ShowOutputPropertiesCommand 22 
#define ShowOutputPropertiesCommand_LabelTitle_RESID 60105
#define ShowOutputPropertiesCommand_LabelDescription_RESID 60106
#define ShowOutputPropertiesCommand_Keytip_RESID 60107
#define ShowOutputPropertiesCommand_TooltipTitle_RESID 60108
#define ShowOutputPropertiesCommand_TooltipDescription_RESID 60109
#define ShowOutputPropertiesCommand_SmallImages_RESID 60110
#define ShowOutputPropertiesCommand_LargeImages_RESID 60111
#define ShowPaletteCommand 23 
#define ShowPaletteCommand_LabelTitle_RESID 60112
#define ShowPaletteCommand_LabelDescription_RESID 60113
#define ShowPaletteCommand_Keytip_RESID 60114
#define ShowPaletteCommand_TooltipTitle_RESID 60115
#define ShowPaletteCommand_TooltipDescription_RESID 60116
#define ShowPaletteCommand_SmallImages_RESID 60117
#define ShowPaletteCommand_LargeImages_RESID 60118
#define ShowCanvasCommand 24 
#define ShowCanvasCommand_LabelTitle_RESID 60119
#define ShowCanvasCommand_LabelDescription_RESID 60120
#define ShowCanvasCommand_Keytip_RESID 60121
#define ShowCanvasCommand_TooltipTitle_RESID 60122
#define ShowCanvasCommand_TooltipDescription_RESID 60123
#define ShowCanvasCommand_SmallImages_RESID 60124
#define ShowCanvasCommand_LargeImages_RESID 60125
#define PaletteFromImageCommand 25 
#define PaletteFromImageCommand_LabelTitle_RESID 60126
#define PaletteFromImageCommand_LabelDescription_RESID 60127
#define PaletteFromImageCommand_Keytip_RESID 60128
#define PaletteFromImageCommand_TooltipTitle_RESID 60129
#define PaletteFromImageCommand_TooltipDescription_RESID 60130
#define PaletteFromImageCommand_SmallImages_RESID 60131
#define PaletteFromImageCommand_LargeImages_RESID 60132
#define ScriptMenuGroup 26 
#define ScriptMenuGroup_LabelTitle_RESID 60133
#define RunScriptCommand 27 
#define RunScriptCommand_LabelTitle_RESID 60134
#define RunScriptCommand_LabelDescription_RESID 60135
#define RunScriptCommand_Keytip_RESID 60136
#define RunScriptCommand_TooltipTitle_RESID 60137
#define RunScriptCommand_TooltipDescription_RESID 60138
#define RunScriptCommand_SmallImages_RESID 60139
#define RunScriptCommand_LargeImages_RESID 60140
#define StopScriptCommand 28 
#define StopScriptCommand_LabelTitle_RESID 60141
#define StopScriptCommand_LabelDescription_RESID 60142
#define StopScriptCommand_Keytip_RESID 60143
#define StopScriptCommand_TooltipTitle_RESID 60144
#define StopScriptCommand_TooltipDescription_RESID 60145
#define StopScriptCommand_SmallImages_RESID 60146
#define StopScriptCommand_LargeImages_RESID 60147
#define OpenScriptCommand 29 
#define OpenScriptCommand_LabelTitle_RESID 60148
#define OpenScriptCommand_LabelDescription_RESID 60149
#define OpenScriptCommand_Keytip_RESID 60150
#define OpenScriptCommand_TooltipTitle_RESID 60151
#define OpenScriptCommand_TooltipDescription_RESID 60152
#define OpenScriptCommand_SmallImages_RESID 60153
#define OpenScriptCommand_LargeImages_RESID 60154
#define EditScriptCommand 30 
#define EditScriptCommand_LabelTitle_RESID 60155
#define EditScriptCommand_LabelDescription_RESID 60156
#define EditScriptCommand_Keytip_RESID 60157
#define EditScriptCommand_TooltipTitle_RESID 60158
#define EditScriptCommand_TooltipDescription_RESID 60159
#define EditScriptCommand_SmallImages_RESID 60160
#define EditScriptCommand_LargeImages_RESID 60161
#define ManageScriptFavoritesCommand 31 
#define ManageScriptFavoritesCommand_LabelTitle_RESID 60162
#define ManageScriptFavoritesCommand_LabelDescription_RESID 60163
#define ManageScriptFavoritesCommand_Keytip_RESID 60164
#define ManageScriptFavoritesCommand_TooltipTitle_RESID 60165
#define ManageScriptFavoritesCommand_TooltipDescription_RESID 60166
#define ManageScriptFavoritesCommand_SmallImages_RESID 60167
#define ManageScriptFavoritesCommand_LargeImages_RESID 60168
#define ViewMenuGroup 32 
#define ViewMenuGroup_LabelTitle_RESID 60169
#define ViewSampleDensity 33 
#define ViewSampleDensity_LabelTitle_RESID 60170
#define ViewSampleDensity_LabelDescription_RESID 60171
#define ViewSampleDensity_Keytip_RESID 60172
#define ViewSampleDensity_TooltipTitle_RESID 60173
#define ViewSampleDensity_TooltipDescription_RESID 60174
#define ViewSampleDensity_SmallImages_RESID 60175
#define ViewSampleDensity_LargeImages_RESID 60176
#define PanModeCommand 34 
#define PanModeCommand_LabelTitle_RESID 60177
#define PanModeCommand_LabelDescription_RESID 60178
#define PanModeCommand_Keytip_RESID 60179
#define PanModeCommand_TooltipTitle_RESID 60180
#define PanModeCommand_TooltipDescription_RESID 60181
#define PanModeCommand_SmallImages_RESID 60182
#define PanModeCommand_LargeImages_RESID 60183
#define RotateModeCommand 35 
#define RotateModeCommand_LabelTitle_RESID 60184
#define RotateModeCommand_LabelDescription_RESID 60185
#define RotateModeCommand_Keytip_RESID 60186
#define RotateModeCommand_TooltipTitle_RESID 60187
#define RotateModeCommand_TooltipDescription_RESID 60188
#define RotateModeCommand_SmallImages_RESID 60189
#define RotateModeCommand_LargeImages_RESID 60190
#define ZoomInCommand 36 
#define ZoomInCommand_LabelTitle_RESID 60191
#define ZoomInCommand_LabelDescription_RESID 60192
#define ZoomInCommand_Keytip_RESID 60193
#define ZoomInCommand_TooltipTitle_RESID 60194
#define ZoomInCommand_TooltipDescription_RESID 60195
#define ZoomInCommand_SmallImages_RESID 60196
#define ZoomInCommand_LargeImages_RESID 60197
#define ZoomOutCommand 37 
#define ZoomOutCommand_LabelTitle_RESID 60198
#define ZoomOutCommand_LabelDescription_RESID 60199
#define ZoomOutCommand_Keytip_RESID 60200
#define ZoomOutCommand_TooltipTitle_RESID 60201
#define ZoomOutCommand_TooltipDescription_RESID 60202
#define ZoomOutCommand_SmallImages_RESID 60203
#define ZoomOutCommand_LargeImages_RESID 60204
#define ViewDensity5 38 
#define ViewDensity5_LabelTitle_RESID 60205
#define ViewDensity10 39 
#define ViewDensity10_LabelTitle_RESID 60206
#define ViewDensity15 40 
#define ViewDensity15_LabelTitle_RESID 60207
#define ViewDensity25 41 
#define ViewDensity25_LabelTitle_RESID 60208
#define ViewDensity50 42 
#define ViewDensity50_LabelTitle_RESID 60209
#define ViewDensity100 43 
#define ViewDensity100_LabelTitle_RESID 60210
#define ViewDensity150 44 
#define ViewDensity150_LabelTitle_RESID 60211
#define ViewDensity250 45 
#define ViewDensity250_LabelTitle_RESID 60212
#define ViewDensity500 46 
#define ViewDensity500_LabelTitle_RESID 60213
#define ViewDensity1000 47 
#define ViewDensity1000_LabelTitle_RESID 60214
#define RecentItemsCommand 48 
#define RecentItemsCommand_LabelTitle_RESID 60215
#define ShowSettingsCommand 49 
#define ShowSettingsCommand_LabelTitle_RESID 60216
#define ShowSettingsCommand_LabelDescription_RESID 60217
#define ShowSettingsCommand_Keytip_RESID 60218
#define ShowSettingsCommand_TooltipTitle_RESID 60219
#define ShowSettingsCommand_TooltipDescription_RESID 60220
#define ShowSettingsCommand_SmallImages_RESID 60221
#define ShowSettingsCommand_LargeImages_RESID 60222
#define ExitCommand 50 
#define ExitCommand_LabelTitle_RESID 60223
#define ExitCommand_LabelDescription_RESID 60224
#define ExitCommand_Keytip_RESID 60225
#define ExitCommand_TooltipTitle_RESID 60226
#define ExitCommand_TooltipDescription_RESID 60227
#define ExitCommand_SmallImages_RESID 60228
#define ExitCommand_LargeImages_RESID 60229
#define AboutCommand 51 
#define AboutCommand_LabelTitle_RESID 60230
#define AboutCommand_LabelDescription_RESID 60231
#define AboutCommand_Keytip_RESID 60232
#define AboutCommand_TooltipTitle_RESID 60233
#define AboutCommand_TooltipDescription_RESID 60234
#define AboutCommand_SmallImages_RESID 60235
#define AboutCommand_LargeImages_RESID 60236
#define HelpCommand 52 
#define HelpCommand_LabelTitle_RESID 60237
#define HelpCommand_LabelDescription_RESID 60238
#define HelpCommand_Keytip_RESID 60239
#define HelpCommand_TooltipTitle_RESID 60240
#define HelpCommand_TooltipDescription_RESID 60241
#define HelpCommand_SmallImages_RESID 60242
#define HelpCommand_LargeImages_RESID 60243
#define FractalFlameSpecsCommand 53 
#define FractalFlameSpecsCommand_LabelTitle_RESID 60244
#define FractalFlameSpecsCommand_LabelDescription_RESID 60245
#define FractalFlameSpecsCommand_TooltipTitle_RESID 60246
#define FractalFlameSpecsCommand_TooltipDescription_RESID 60247
#define FractalFlameSpecsCommand_SmallImages_RESID 60248
#define FractalFlameSpecsCommand_LargeImages_RESID 60249
#define DonateCommand 54 
#define DonateCommand_LabelTitle_RESID 60250
#define DonateCommand_LabelDescription_RESID 60251
#define DonateCommand_TooltipTitle_RESID 60252
#define DonateCommand_TooltipDescription_RESID 60253
#define DonateCommand_SmallImages_RESID 60254
#define DonateCommand_LargeImages_RESID 60255
#define ShowTransparencyCommand 55 
#define ShowTransparencyCommand_LabelTitle_RESID 60256
#define ShowTransparencyCommand_LabelDescription_RESID 60257
#define ShowTransparencyCommand_Keytip_RESID 60258
#define ShowTransparencyCommand_TooltipTitle_RESID 60259
#define ShowTransparencyCommand_TooltipDescription_RESID 60260
#define ShowTransparencyCommand_SmallImages_RESID 60261
#define ShowGuidelinesCommand 56 
#define ShowGuidelinesCommand_LabelTitle_RESID 60262
#define ShowGuidelinesCommand_LabelDescription_RESID 60263
#define ShowGuidelinesCommand_Keytip_RESID 60264
#define ShowGuidelinesCommand_TooltipTitle_RESID 60265
#define ShowGuidelinesCommand_TooltipDescription_RESID 60266
#define ShowGuidelinesCommand_SmallImages_RESID 60267
#define ShowIconsCommand 57 
#define ShowIconsCommand_LabelTitle_RESID 60268
#define ShowIconsCommand_LabelDescription_RESID 60269
#define ShowIconsCommand_Keytip_RESID 60270
#define ShowIconsCommand_TooltipTitle_RESID 60271
#define ShowIconsCommand_TooltipDescription_RESID 60272
#define ShowIconsCommand_SmallImages_RESID 60273
