//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xyrus.Apophysis.Windows.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xyrus.Apophysis.Windows.Controls.ControlResources", typeof(ControlResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DragGridNameColumnHeader {
            get {
                return ResourceManager.GetString("DragGridNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string DragGridValueColumnHeader {
            get {
                return ResourceManager.GetString("DragGridValueColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate plugin directory.
        /// </summary>
        internal static string LocatePluginDirectoryHelpString {
            get {
                return ResourceManager.GetString("LocatePluginDirectoryHelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render all in &quot;{0}&quot;.
        /// </summary>
        internal static string RenderBatchWindowTitleWithFlames {
            get {
                return ResourceManager.GetString("RenderBatchWindowTitleWithFlames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render all.
        /// </summary>
        internal static string RenderBatchWindowTitleWithoutFlames {
            get {
                return ResourceManager.GetString("RenderBatchWindowTitleWithoutFlames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render  &quot;{0}&quot;.
        /// </summary>
        internal static string RenderSingleWindowTitleWithFlame {
            get {
                return ResourceManager.GetString("RenderSingleWindowTitleWithFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Render.
        /// </summary>
        internal static string RenderSingleWindowTitleWithoutFlame {
            get {
                return ResourceManager.GetString("RenderSingleWindowTitleWithoutFlame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select autosave target....
        /// </summary>
        internal static string SelectAutosaveTarget {
            get {
                return ResourceManager.GetString("SelectAutosaveTarget", resourceCulture);
            }
        }
    }
}
